import { Nunito_Sans } from "next/font/google";
import "./globals.css";

const font = Nunito_Sans({ subsets: ["latin"] });

export const metadata = {
    title: "ContactBook",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={font.className}>{children}</body>
        </html>
    );
}
